apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque # Generic secret
data:
  password: c3VwZXJzZWNyZXQ=  # echo -n 'supersecret' | base64
  api-key: YXBpa2V5Cg==
stringData:
  username: admin
immutable: true