apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: exam
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: httpd
          image: httpd:alpine
          ports:
            - containerPort: 80