apiVersion: v1
kind: Pod
metadata:
  name: shared-network-pod
spec:
  containers:
  - name: app-container
    image: nginx
    ports:
    - containerPort: 80
  - name: client-sidecar
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do wget -q -O- localhost:80; sleep 10; done"]